import { FormEvent, useState } from 'react';
import { Link, useNavigate } from 'react-router-dom';
import { ArrowRight, CircleDot, LockKeyhole, ShieldCheck, Sparkles } from 'lucide-react';
import { toast } from 'sonner';
import { useAuth } from '../context/AuthContext';

export default function Auth({ mode }: { mode: 'login' | 'signup' }) {
  const isLogin=mode==='login';
  const [name,setName]=useState(''); const [email,setEmail]=useState(''); const [password,setPassword]=useState('');
  const {login,register,openDemo,loading}=useAuth(); const navigate=useNavigate();
  async function submit(e:FormEvent){e.preventDefault();try{const p=isLogin?await login(email,password):await register(name,email,password);toast.success(isLogin?`Welcome back, ${p.full_name}`:'Account created');navigate(p.role==='admin'?'/admin':(p.role==='user'&&isLogin?'/dashboard':'/subscribe'));}catch(err){toast.error(err instanceof Error?err.message:'Something went wrong');}}
  async function demo(role:'user'|'admin'){try{const p=await openDemo(role);toast.success(role==='admin'?'Admin demo opened':'User demo opened');navigate(p.role==='admin'?'/admin':'/dashboard');}catch(err){toast.error(err instanceof Error?err.message:'Unable to open demo');}}
  return <div className="auth-page container"><div className="auth-panel glass-card"><div className="auth-brand"><span className="brand-mark"><CircleDot size={15}/></span><span>impact<span>play</span></span></div><span className="eyebrow">{isLogin?'WELCOME BACK':'START WITH PURPOSE'}</span><h1>{isLogin?'Pick up where you left off.':'Build your impact loop.'}</h1><p>{isLogin?'Access your match form, charity settings, and monthly reward activity.':'Create a member account, then choose a plan and cause.'}</p><form onSubmit={submit} className="form-stack">{!isLogin&&<label>Full name<input value={name} onChange={e=>setName(e.target.value)} placeholder="Your name" required/></label>}<label>Email<input type="email" value={email} onChange={e=>setEmail(e.target.value)} placeholder="you@example.com" required/></label><label>Password<input type="password" value={password} onChange={e=>setPassword(e.target.value)} placeholder="••••••••" minLength={8} required/></label><button className="btn btn-primary full" disabled={loading}>{loading?'Working…':isLogin?'Log in':'Create account'} <ArrowRight size={16}/></button></form><div className="auth-note"><LockKeyhole size={15}/> Real accounts use Supabase Auth. Recruiter demo access requires no credentials.</div>{isLogin&&<div className="auth-demo-block"><div><span className="eyebrow">RECRUITER DEMO</span><strong>Explore the working product instantly</strong><span>No email, password, or setup required.</span></div><div className="auth-demo-actions"><button type="button" className="btn btn-secondary" onClick={()=>demo('user')} disabled={loading}><Sparkles size={14}/> User Demo</button><button type="button" className="btn btn-secondary" onClick={()=>demo('admin')} disabled={loading}><ShieldCheck size={14}/> Admin Demo</button></div></div>}<div className="auth-switch">{isLogin?<>New here? <Link to="/signup">Create an account</Link></>:<>Already registered? <Link to="/login">Log in</Link></>}</div></div></div>;
}
