import { Search, HeartHandshake, ArrowRight } from 'lucide-react';
import { useMemo, useState } from 'react';
import { Link } from 'react-router-dom';
import PageHeader from '../components/PageHeader';
import SectionReveal from '../components/SectionReveal';
import { loadDemoState } from '../lib/demoData';
import { useAuth } from '../context/AuthContext';
import { toast } from 'sonner';

export default function Charities(){ const {profile}=useAuth(); const [query,setQuery]=useState(''); const [selected,setSelected]=useState<string>(()=>loadDemoState().subscription.charity_id); const [percent,setPercent]=useState(loadDemoState().subscription.charity_percentage); const state=loadDemoState(); const list=useMemo(()=>state.charities.filter(c=>c.name.toLowerCase().includes(query.toLowerCase())||c.description.toLowerCase().includes(query.toLowerCase())),[query,state.charities]);
 function save(){const next=loadDemoState();next.subscription.charity_id=selected;next.subscription.charity_percentage=percent;localStorage.setItem('impactplay-demo-state',JSON.stringify(next));toast.success(`Your ${percent}% contribution now supports ${state.charities.find(c=>c.id===selected)?.name}`)}
 return <div><PageHeader eyebrow="CHARITY DIRECTORY" title="Choose where your contribution lands." body="Discover causes, compare impact, and direct at least 10% of your subscription to the organization that matters to you."/><div className="container"><div className="toolbar glass-card"><div className="search"><Search size={16}/><input value={query} onChange={e=>setQuery(e.target.value)} placeholder="Search charities..."/></div><div className="contribution-control"><span>Contribution</span><input type="range" min="10" max="50" step="5" value={percent} onChange={e=>setPercent(Number(e.target.value))}/><strong>{percent}%</strong></div></div><div className="charity-directory">{list.map((c,i)=><SectionReveal key={c.id} delay={i*.04}><div className={`charity-detail-card glass-card ${selected===c.id?'selected':''}`}><img src={c.image_url} alt=""/><div className="charity-detail-copy"><div className="tiny-tag">{c.featured?'FEATURED CAUSE':'COMMUNITY CAUSE'}</div><h2>{c.name}</h2><p>{c.description}</p><div className="impact-chip"><HeartHandshake size={15}/>{c.impact_metric}</div><div className="charity-actions"><button className={selected===c.id?'btn btn-primary':'btn btn-secondary'} onClick={()=>setSelected(c.id)}>{selected===c.id?'Selected':'Choose this cause'}</button>{!profile && <Link className="tiny-link" to="/signup">Join to contribute <ArrowRight size={13}/></Link>}</div></div></div></SectionReveal>)}</div>{profile&&<div className="save-bar glass-card"><div><strong>{percent}% going to {state.charities.find(c=>c.id===selected)?.name}</strong><span>Minimum allowed: 10%</span></div><button className="btn btn-primary" onClick={save}>Save preference <ArrowRight size={15}/></button></div>}</div></div>;
}
