import { Link } from 'react-router-dom';
import { ArrowRight, CalendarDays, CircleDot, HeartHandshake, Sparkles, Trophy, TrendingUp } from 'lucide-react';
import SectionReveal from '../components/SectionReveal';
import Pill from '../components/Pill';
import { loadDemoState } from '../lib/demoData';
import { useAuth } from '../context/AuthContext';

export default function Dashboard() {
  const { profile } = useAuth(); const state = loadDemoState(profile?.role === 'admin');
  const charity = state.charities.find(c => c.id === state.subscription.charity_id)!;
  const avg = (state.scores.reduce((a,s)=>a+s.score,0)/Math.max(1,state.scores.length)).toFixed(1);
  return <div className="dashboard-page container"><div className="page-top"><div><span className="eyebrow">MEMBER CONSOLE</span><h1>Good to see you, {profile?.full_name.split(' ')[0]}.</h1><p>Your cricket form, purpose, and participation — in one place.</p></div><Link className="btn btn-primary" to="/scores">Log a match <ArrowRight size={16}/></Link></div>
    <div className="dashboard-grid"><SectionReveal><div className="metric-card glass-card accent"><span>Subscription</span><strong>Active</strong><small>Renews 20 Oct 2026</small><Pill>Monthly</Pill></div></SectionReveal><SectionReveal delay={.04}><div className="metric-card glass-card"><span>Average Form Score</span><strong>{avg}</strong><small>1–45 · latest 5 matches</small><div className="metric-trend"><TrendingUp size={15}/> +6.2% vs prior</div></div></SectionReveal><SectionReveal delay={.08}><div className="metric-card glass-card"><span>Current winnings</span><strong>₹16,800</strong><small>1 pending verification</small><Link to="/winners" className="tiny-link">Review status <ArrowRight size={13}/></Link></div></SectionReveal></div>
    <div className="dashboard-columns"><SectionReveal><div className="panel glass-card"><div className="panel-head"><div><span className="eyebrow">YOUR MATCH FORM</span><h2>Latest five matches</h2></div><Link className="tiny-link" to="/scores">Manage <ArrowRight size={13}/></Link></div><div className="score-list">{state.scores.map((s,i)=><div className="score-row cricket-score-row" key={s.id}><div className="score-date"><CalendarDays size={14}/><span>{new Date(s.score_date).toLocaleDateString('en-IN',{day:'2-digit',month:'short'})}</span></div><div className="match-summary"><strong>{s.runs} runs · {s.wickets} wkts</strong><small>{s.format} · {s.result}</small></div><strong className="form-score-number">{s.score}</strong><span className="score-bar"><span style={{width:`${Math.round(s.score/45*100)}%`}} /></span><span className="score-rank">{i===0?'Latest':`#${i+1}`}</span></div>)}</div></div></SectionReveal>
      <SectionReveal delay={.08}><div className="panel glass-card"><div className="panel-head"><div><span className="eyebrow">YOUR CAUSE</span><h2>{charity.name}</h2></div><HeartHandshake size={20}/></div><div className="charity-mini"><img src={charity.image_url} alt=""/><div><strong>{state.subscription.charity_percentage}%</strong><span>of your membership directed</span><p>{charity.impact_metric}</p></div></div><Link className="btn btn-secondary full" to="/charities">Change charity <ArrowRight size={15}/></Link></div></SectionReveal></div>
    <SectionReveal><div className="panel glass-card draw-panel"><div><span className="eyebrow">NEXT DRAW</span><h2>October 2026</h2><p>Simulation ready. Publication is controlled by an administrator.</p></div><div className="draw-numbers">{state.draws[1].numbers.map(n=><span key={n}>{n.toString().padStart(2,'0')}</span>)}</div><div><Pill tone="orange">SIMULATED</Pill><div className="tiny-muted">Eligible members: {state.draws[1].eligible_subscribers.toLocaleString()}</div></div></div></SectionReveal>
    <SectionReveal delay={.06}><div className="dashboard-tip glass-card"><CircleDot size={17}/><div><strong>Form Score insight</strong><span>Your recent matches combine batting, bowling and result into one normalized 1–45 signal.</span></div><Sparkles size={16}/></div></SectionReveal>
  </div>;
}
