import { useState } from 'react';
import { CheckCircle2, FileUp, Trophy } from 'lucide-react';
import PageHeader from '../components/PageHeader';
import SectionReveal from '../components/SectionReveal';
import Pill from '../components/Pill';
import { loadDemoState } from '../lib/demoData';
import { toast } from 'sonner';

export default function Winners(){const [state,setState]=useState(loadDemoState()); const winner=state.winners[0]; function upload(){const next=loadDemoState(); next.winners=[{...next.winners[0], proof_url:'demo-proof-uploaded'}]; localStorage.setItem('impactplay-demo-state',JSON.stringify(next));setState(next);toast.success('Match scorecard uploaded. Status moved to pending review.')} return <div><PageHeader eyebrow="WINNER VERIFICATION" title="Your payout, with a visible trail." body="Eligible winners upload a match scorecard for admin review. The payment lifecycle moves from pending to paid after verification."/><div className="container winner-page"><SectionReveal><div className="winner-card glass-card"><div className="winner-icon"><Trophy size={26}/></div><div><span className="eyebrow">SEPTEMBER 2026 DRAW</span><h2>{winner.amount.toLocaleString('en-IN',{style:'currency',currency:'INR',maximumFractionDigits:0})}</h2><p>{winner.match_type} match · current payment status {winner.payment_status}</p></div><Pill tone={winner.verification_status==='approved'?'green':'orange'}>{winner.verification_status.toUpperCase()}</Pill></div></SectionReveal><SectionReveal delay={.08}><div className="panel glass-card"><div className="panel-head"><div><span className="eyebrow">PROOF OF PERFORMANCE</span><h2>Upload a match scorecard</h2></div><FileUp size={19}/></div><div className="upload-zone" onClick={upload}><input type="file" accept="image/*" onChange={upload}/><CheckCircle2 size={22}/><strong>{winner.proof_url?'Scorecard uploaded':'Drop a match scorecard here'}</strong><span>{winner.proof_url?'Pending admin review':'PNG or JPG · proof is only requested from winners'}</span></div></div></SectionReveal></div></div>}
