import { Check, Eye, X } from 'lucide-react';
import { toast } from 'sonner';
import { useState } from 'react';
import PageHeader from '../../components/PageHeader';
import SectionReveal from '../../components/SectionReveal';
import Pill from '../../components/Pill';
import { loadDemoState } from '../../lib/demoData';

export default function AdminWinners(){const [state,setState]=useState(loadDemoState(true));function act(status:'approved'|'rejected'|'paid'){const next=loadDemoState(true);const winner={...next.winners[0]};if(status==='paid')winner.payment_status='paid';else winner.verification_status=status;next.winners=[winner];localStorage.setItem('impactplay-demo-state',JSON.stringify(next));setState(next);toast.success(`Winner ${status}`)}const w=state.winners[0];return <div><PageHeader eyebrow="ADMIN · WINNERS" title="Verify and pay with confidence." body="Review proof, approve or reject a submission, then complete payout when verification is successful."/><div className="container"><SectionReveal><div className="panel glass-card"><div className="winner-admin-card"><div className="winner-thumb"><img src={w.proof_url?.startsWith('http')?w.proof_url:'https://images.unsplash.com/photo-1585435557343-3b092031a831?auto=format&fit=crop&w=500&q=80'} alt="Proof"/></div><div className="winner-admin-copy"><span className="eyebrow">{w.match_type.toUpperCase()}</span><h2>{w.user_name}</h2><strong>₹{w.amount.toLocaleString('en-IN')}</strong><div className="status-pills"><Pill tone={w.verification_status==='approved'?'green':'orange'}>{w.verification_status}</Pill><Pill>{w.payment_status}</Pill></div></div><div className="winner-actions"><button className="btn btn-secondary"><Eye size={15}/> View proof</button><button className="icon-btn success" onClick={()=>act('approved')}><Check size={16}/></button><button className="icon-btn danger" onClick={()=>act('rejected')}><X size={16}/></button><button className="btn btn-primary" onClick={()=>act('paid')}>Mark paid</button></div></div></div></SectionReveal></div></div>}
