import { useState } from 'react';
import { Dices, Play, Send, RefreshCcw } from 'lucide-react';
import { toast } from 'sonner';
import PageHeader from '../../components/PageHeader';
import SectionReveal from '../../components/SectionReveal';
import Pill from '../../components/Pill';
import { generateDraw, calculatePrizePools } from '../../lib/drawEngine';
import { loadDemoState } from '../../lib/demoData';

export default function AdminDraws(){const [type,setType]=useState<'random'|'algorithmic'>('random');const [numbers,setNumbers]=useState(loadDemoState(true).draws[1].numbers);const pools=calculatePrizePools(100000,38400);function simulate(){const scores=loadDemoState(true).scores;setNumbers(generateDraw(type,scores));toast.success(`${type} simulation complete`)}return <div><PageHeader eyebrow="ADMIN · REWARD ENGINE" title="Simulate, inspect, publish." body="Switch between random and algorithmic modes, run a simulation, inspect prize pools, and publish results."/><div className="container"><div className="admin-draw-grid"><SectionReveal><div className="panel glass-card"><div className="panel-head"><div><span className="eyebrow">DRAW CONFIG</span><h2>October 2026</h2></div><Dices size={19}/></div><div className="toggle-row"><button onClick={()=>setType('random')} className={type==='random'?'toggle active':'toggle'}>Random</button><button onClick={()=>setType('algorithmic')} className={type==='algorithmic'?'toggle active':'toggle'}>Algorithmic</button></div><div className="draw-sim-box">{numbers.map(n=><span key={n}>{n.toString().padStart(2,'0')}</span>)}</div><div className="admin-action-row"><button className="btn btn-secondary" onClick={simulate}><RefreshCcw size={15}/> Run simulation</button><button className="btn btn-primary" onClick={()=>toast.success('Draw published in demo workflow')}><Send size={15}/> Publish</button></div></div></SectionReveal><SectionReveal delay={.08}><div className="panel glass-card"><div className="panel-head"><div><span className="eyebrow">POOL CALCULATION</span><h2>Example ₹1,00,000 pool</h2></div><Pill tone="orange">AUTOMATIC</Pill></div><div className="pool-line"><span>5-number jackpot</span><strong>₹{pools.jackpot.toLocaleString('en-IN')}</strong><small>40% + rollover</small></div><div className="pool-line"><span>4-number tier</span><strong>₹{pools.four.toLocaleString('en-IN')}</strong><small>35%</small></div><div className="pool-line"><span>3-number tier</span><strong>₹{pools.three.toLocaleString('en-IN')}</strong><small>25%</small></div><div className="audit-box"><Play size={14}/> Pool math is deterministic and suitable for server-side enforcement.</div></div></SectionReveal></div></div></div>}
